### PR TITLE
Add upload from remote server

### PR DESCRIPTION
**Pull request by alesyalis**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by alesyalis** [comment]
recheckcla

**Comment by alesyalis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alesyalis** [comment]
recheckcla

**Comment by alesyalis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alesyalis** [comment]
recheckcla

**Comment by ghost** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Ukrainiangirl — APPROVED** [review]

**Review by vldmrklnk — APPROVED** [review]

**Review by Evgeniy-Sinicin — APPROVED** [review]

**Pull request merged**
